# Generated by Django 5.1.6 on 2025-02-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminApp", "0001_initial"),
        ("loginRegistrationApp", "0002_auto_20250219_1030"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="labels",
            field=models.ManyToManyField(
                related_name="events", to="adminApp.eventlabel"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="tags",
            field=models.ManyToManyField(related_name="events", to="adminApp.eventtag"),
        ),
    ]
