# Generated by Django 5.1.6 on 2025-02-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminApp", "0002_rename_name_eventlabel_eventlabelname_and_more"),
        ("loginRegistrationApp", "0003_events_labels_events_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="labels",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="adminApp.eventlabel"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="adminApp.eventtag"
            ),
        ),
    ]
