# Generated by Django 4.2.19 on 2025-03-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loginRegistrationApp", "0004_alter_events_labels_alter_events_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="numberOfAttenders",
            new_name="numberOfAttendees",
        ),
        migrations.RemoveField(
            model_name="userattendingevent",
            name="eventId",
        ),
        migrations.RemoveField(
            model_name="userattendingevent",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="userinterests",
            name="interestId",
        ),
        migrations.RemoveField(
            model_name="userinterests",
            name="userId",
        ),
        migrations.RemoveField(
            model_name="usertypes",
            name="userId",
        ),
        migrations.AddField(
            model_name="events",
            name="attendees",
            field=models.ManyToManyField(
                related_name="events",
                through="loginRegistrationApp.UserAttendingEvent",
                to="loginRegistrationApp.users",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="eventSlug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userattendingevent",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loginRegistrationApp.events",
            ),
        ),
        migrations.AddField(
            model_name="userattendingevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loginRegistrationApp.users",
            ),
        ),
        migrations.AddField(
            model_name="userinterests",
            name="interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loginRegistrationApp.interests",
            ),
        ),
        migrations.AddField(
            model_name="userinterests",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interests",
                to="loginRegistrationApp.users",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="userSlug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertypes",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_types",
                to="loginRegistrationApp.users",
            ),
        ),
    ]
