# Generated by Django 4.2.19 on 2025-03-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "loginRegistrationApp",
            "0005_rename_numberofattenders_events_numberofattendees_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="eventSlug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="userattendingevent",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loginRegistrationApp.events",
            ),
        ),
        migrations.AlterField(
            model_name="userattendingevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loginRegistrationApp.users",
            ),
        ),
        migrations.AlterField(
            model_name="userinterests",
            name="interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="loginRegistrationApp.interests",
            ),
        ),
        migrations.AlterField(
            model_name="userinterests",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interests",
                to="loginRegistrationApp.users",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="userSlug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="usertypes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_types",
                to="loginRegistrationApp.users",
            ),
        ),
    ]
