# Generated by Django 5.1.6 on 2025-03-16 15:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistrationApp', '0006_alter_events_eventslug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
