# Generated by Django 5.1.6 on 2025-02-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventlabel",
            old_name="name",
            new_name="eventLabelName",
        ),
        migrations.RenameField(
            model_name="eventtag",
            old_name="name",
            new_name="eventTagName",
        ),
        migrations.AlterModelTable(
            name="eventlabel",
            table="event_label",
        ),
        migrations.AlterModelTable(
            name="eventtag",
            table="event_tag",
        ),
    ]
