# Generated by Django 5.1.6 on 2025-02-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminApp", "0002_rename_name_eventlabel_eventlabelname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlabel",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventtag",
            name="required",
            field=models.BooleanField(default=False),
        ),
    ]
