# Generated by Django 5.1.6 on 2025-03-05 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("loginRegistrationApp", "0004_alter_events_labels_alter_events_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("booked", "Booked"), ("cancelled", "Cancelled")],
                        default="booked",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loginRegistrationApp.users",
                    ),
                ),
                (
                    "digital_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memberApp.digitalmodule",
                    ),
                ),
            ],
        ),
    ]
