# Generated by Django 5.1.6 on 2025-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="booked_at",
            new_name="booked_on",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
        migrations.RemoveField(
            model_name="digitalmodule",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="digitalmodule",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="digitalmodule",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="digitalmodule",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
