# Generated by Django 5.1.6 on 2025-03-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loginRegistrationApp", "0004_alter_events_labels_alter_events_tags"),
        ("memberApp", "0002_rename_booked_at_booking_booked_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalContentModule",
            fields=[
                ("module_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "duration",
                    models.PositiveIntegerField(help_text="Duration in minutes"),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "digital_content_modules",
            },
        ),
        migrations.RemoveField(
            model_name="booking",
            name="digital_module",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="user",
        ),
        migrations.CreateModel(
            name="ModuleBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_booked", models.BooleanField(default=False)),
                ("date_booked", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="memberApp.digitalcontentmodule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loginRegistrationApp.users",
                    ),
                ),
            ],
            options={
                "db_table": "module_bookings",
            },
        ),
        migrations.DeleteModel(
            name="DigitalModule",
        ),
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
