# Generated by Django 5.1.6 on 2025-03-09 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberApp", "0004_benefit_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="benefit",
            name="membership",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="benefits",
                to="memberApp.membership",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
